### ISSUE TITLE
Any possibility of making this 3.4 compatible?

### ISSUE THREAD

**Issue by versae** [urschrei/simplification#1]
We are tied to a CentOS only supporting 3.4 but really love the library and its performance. It would be great to have it working with `pip install` for 3.4.

**Comment by urschrei** [comment]
I've just pushed v0.2.8 to PyPI, which includes a `manylinux1` Python 3.4 wheel. Let me know if it works for you!

**Comment by versae** [comment]
Thank you! I'll test it in a second 🚀

**Comment by versae** [comment]
It works great! We not got Travis back, although also noticed that for Mac there is only support for 2.7 and 3.6 in the last release.

**Comment by urschrei** [comment]
Oops, yep. I'm testing an OS X 3.4 build at the moment, and I'll push a release if it works…

**Comment by versae** [comment]
That's great, I really appreciate it. The only one missing from the complete matrix (in case you wanted it all) seems to be just `simplification-v0.2.9-x86_64-apple-darwin-cp35.tar.gz`.

**Comment by urschrei** [comment]
v0.2.9 with an OS X Python 3.4 wheel is live on PyPI now. I'll have a look at a 3.5 release when I get a chance. Also, I'm delighted to see some Rust code go live in Histonets – it looks like a  great project.

**Comment by urschrei** [comment]
I also took the opportunity to add Numpy support (0.2.11, on PyPI now), so if you input numpy arrays, you'll get numpy arrays back, which should be noticeably faster for large lines.

**Comment by versae** [comment]
Awesome! Thanks, man. I feel like this issue is ready to be closed. Glad there are libraries like yours to use in projects like Histonets. And kudos for the numpy support 👍  Keep up the good work!
