### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by wagenrace** [urschrei/simplification#12]
Is simplification ready for a python 3.8 release?

**Comment by urschrei** [comment]
On Windows? No, as it's not available on the Appveyor build system.

**Comment by whentheworldfallsapart** [comment]
I haven't used Appveyor, so forgive if i am mistaken but it looks like Python 3.8 is available [Git Issue](https://github.com/appveyor/ci/issues/3142)
added in november 2019 [release update](https://www.appveyor.com/updates/2019/11/08/)
here are the [current images](https://www.appveyor.com/docs/windows-images-software/#python), it looks like 3.8.6 is now available 
Any chance of nudging this?

**Comment by urschrei** [comment]
0.5.2 is available on PyPI now, but Python 3.8 support on Windows is 64-bit only: https://pypi.org/project/simplification/0.5.2/

(I have no idea why the 32-bit version won't build, and am extremely time-constrained at the moment. Sorry!)

**Comment by whentheworldfallsapart** [comment]
Oh no worries, x64 works for me. Thank you so much!
