### ISSUE TITLE
Python 3.9 release

### ISSUE THREAD

**Issue by jck** [urschrei/simplification#13]
Is simplification ready for a python 3.9 release?

**Comment by mbway** [comment]
(for other people encountering problems:) when trying to install in a python3.9 environment I get
```
$ python --version
Python 3.9.1
$ pip install --upgrade simplification
ERROR: Could not find a version that satisfies the requirement simplification
ERROR: No matching distribution found for simplification
```
which I assume is because the package doesn't have 3.9 listed as a supported version yet. I can install simplification in a python 3.8 environment without any issues.

**Comment by urschrei** [comment]
Released to PyPI (macOS and Linux only)
