### ISSUE TITLE
Install archiconda environment on aarch64 (NVIDIA AGX)

### ISSUE THREAD

**Issue by sivashankar28** [urschrei/simplification#18]
Hi I am trying to install simplifyline on a conda environment on my NVIDIA AGX (aarch64). I am not sure how to do this and would appreciate any assistance

**Comment by urschrei** [comment]
Simplification is not available on aarch64 at the moment.

**Comment by sivashankar28** [comment]
Okay thank you, please let me know when you do have it available, I would love to use it. Thank you!

**Comment by urschrei** [comment]
Hi @sivashankar28, 0.5.22 has just been released, which I **hope** works correctly on M1: https://pypi.org/project/simplification/0.5.22

Please try it and let me know.
