### ISSUE TITLE
Can't install any specific version of the library from PyPI

### ISSUE THREAD

**Issue by versae** [urschrei/simplification#2]
First, thank for the library, it's blazingly fast and we rely a lot on it.

However, I recently updated a project that depended on `simplification` and it broke in Travis. I realized the only dependency I had not pinned down was `simplification`, so I try to pin it down but it didn't work. Apparently, `v0.3.2` is only available for Python 3.5, while for Python 3.6 and 3.4 the latest available is `v0.2.11`, making CI testing and packaging `simplification` as part of another app very complicated. Is there going to be a release for the `v0.3.3` that is available for all Python 3.4, 3.5, and 3.6 in PyPI at least for Linux and Mac?

**Comment by urschrei** [comment]
For some reason, I built and released v0.3.3 in March, but never uploaded it to PyPI. That release – now live – should cover 2.7, 3.4, 3.5, and 3.6. Sorry!

**Comment by versae** [comment]
Thanks for the quick reply! Apparently, it's still not available for 3.5. For 3.4 and 3.6 it works just fine.

**Comment by urschrei** [comment]
OK, try now?

**Comment by versae** [comment]
Sorry, still can't make it work. Am I doing something wrong?
```
(in a Python 3.4 virtualenv)
$ python --version
Python 3.4.6
$ pip install simplification==0.3.7
Collecting simplification==0.3.7
  Could not find a version that satisfies the requirement simplification==0.3.7 (from versions: 0.2.9, 0.2.10)
No matching distribution found for simplification==0.3.7

```

```
(in a Python 3.5 virtualenv)
$ python --version
Python 3.5.5
$ pip install simplification==0.3.7
Collecting simplification==0.3.7
  Could not find a version that satisfies the requirement simplification==0.3.7 (from versions: 0.1.1, 0.1.2, 0.1.6, 0.2.1)
No matching distribution found for simplification==0.3.7
```
The `pip` version is 10.0.1 in both cases.

Thank again for your help!

**Comment by urschrei** [comment]
I'm really confused by this:

- I'm building the wheels using multibuild, in a manylinux1 container on Travis
- The build process successfully installs and tests the freshly-built wheels:
    - [3.4](https://travis-ci.org/urschrei/simplification/jobs/378060579#L757)
    - [3.5](https://travis-ci.org/urschrei/simplification/jobs/378060579#L771)
- they're [definitely available](https://pypi.org/project/simplification/#files) on PyPI, and it's identifying the Python versions correctly
- There are no changes between the metadata of 0.2.10 and 0.3.7 except for the `bdist_wheel` version (the `Generator` key in `WHEEL`)
- the filenames of the wheels are the same (again, only the version is different).

I'll have to ask on the wheel-builders mailing list. What platforms (Linux version etc are you trying to install on?)

**Comment by versae** [comment]
Haven't deployed on Linux or tried on Travis yet. For development I use a Mac:
```
$ pyenv --version
pyenv 1.2.4
$ defaults read loginwindow SystemVersionStampAsString
10.13.4
$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
$ sysctl hw |grep 64bit
hw.cpu64bit_capable: 1
```
By looking at the PyPI files you linked, it seems like the wheels for cp34 and cp35 are missing for Mac OSX.

**Comment by urschrei** [comment]
I should probably have asked about the platform in the first place. `0.3.8` should (hopefully) have a wheel for every platform…

**Comment by versae** [comment]
Awesome! It does work now. Thank you so much :)
