### ISSUE TITLE
Simplification build for arm64 python docker image

### ISSUE THREAD

**Issue by Pitirus** [urschrei/simplification#23]
Is there a possibility to get a python package for arm64 python docker image?
I'm working on M1 Mac and all of our services are containerized.
To reproduce (on M1 Macs) you can use following commands:
```
docker run -it --entrypoint bash python
# then inside the container
pip install simplification
```

I get following output:
```
ERROR: Could not find a version that satisfies the requirement simplification (from versions: none)
ERROR: No matching distribution found for simplification
```

**Comment by urschrei** [comment]
Last time I checked, there wasn't a suitable arm64 manylinux docker image available to build https://github.com/urschrei/rdp, which is a blocker, unfortunately.

**Comment by Pitirus** [comment]
Doesn't work for me. In the simple PyPI index [link](https://pypi.org/simple/simplification/) I can't see wheel for manylinux2014_aarch64
![image](https://user-images.githubusercontent.com/19556669/165563649-a0869461-5593-470c-b7eb-d78ba8cab6b5.png)

**Comment by urschrei** [comment]
There hasn't been any progress on an aarch64 Linux wheel. Aarch64 is currently only supported on macOS.

**Comment by Mogost** [comment]
Also interested in arm64 for linux. Looks like we may have this arch for simplification as easy as for mac. https://github.com/pypa/cibuildwheel/blob/61999a886bc05c7d09faaed78fd259f27849d259/docs/options.md with CIBW_ARCHS_LINUX arg
