### ISSUE TITLE
Extension to 3D lines

### ISSUE THREAD

**Issue by mawanda-jun** [urschrei/simplification#43]
Hi and thank you for your hard work.
I'd like to ask you if it's possible to expand this work to 3D lines. I'm not sure of the impact of this feature in this work.

Thank you in advance,
Giovanni

**Comment by urschrei** [comment]
Simplification uses algorithms from Rust's `geo` library, which is 2D only with no plans to add support for 3 dimensions, so this won't be possible.

**Comment by mawanda-jun** [comment]
Hi,
Thank your for your fast response. No worries! 

Great work, continue on this path!

Greetings,
Giovanni

**Comment by district10** [comment]
I have a c++/python version of rdp, supports 3D: https://github.com/cubao/pybind11-rdp

(It's fast but I havent't benchmarked with this rust version)
