### ISSUE TITLE
Adding to conda-forge

### ISSUE THREAD

**Issue by cheginit** [urschrei/simplification#44]
Is there any plan to add `simplification` to the conda-forge channel? It would be great if this happens so other packages that are available on conda-forge can use it as a dependency in their build.

**Comment by urschrei** [comment]
I don't use Anaconda and don't have time to learn how, so it won't happen unless someone else builds it I'm afraid.

**Comment by cheginit** [comment]
I see. Makes sense. Thanks for letting me know.

**Comment by theroggy** [comment]
This was closed as completed, but I don't seem to find the package on conda-forge. Has it been published in another conda channel or ?

**Comment by urschrei** [comment]
I closed as I am not a Conda user and nobody else was interested in making the package available.

**Comment by theroggy** [comment]
Ah, ok.

**Comment by cheginit** [comment]
It's now available on `conda-forge`.
