### ISSUE TITLE
Python 3.7 Windows build

### ISSUE THREAD

**Issue by phil65** [urschrei/simplification#5]
Sorry to bug you, would it be possible to provide a "simplification" Wheel for Windows Py3.7?

**Comment by urschrei** [comment]
The conda distribution in Appveyor doesn't yet provide Python 3.7 support, so it's not possible at the moment, presumably related to this issue: https://github.com/conda/conda/issues/7975

**Comment by phil65** [comment]
Okay, thank you for the info!

**Comment by urschrei** [comment]
(We might as well leave this open – the upstream issue will be fixed sooner rather than later I'm sure)

**Comment by phil65** [comment]
Fixed. Thanks! :)
