### ISSUE TITLE
Before/After metadata when simplified points are returned

### ISSUE THREAD

**Issue by telemmaite** [urschrei/simplification#6]
Let`s say is we have of not only X,Y points but also heading and timestamp of the point.
So input looks like [[X,Y,HEADING,TIMESTAMP]]
After X,Y simplification, can we still return or somehow intersect with initial data-set ?

**Comment by urschrei** [comment]
No, because the foreign function (in https://github.com/georust/geo) doesn't currently return the indices of the retained points, only the points themselves. It's certainly possible to return the indices, but that's work that will have to be done on the Rust library.

**Comment by eLvErDe** [comment]
Hello,

+1 for this feature. In the meanwhile could you advice us how to workaround this ? Iterating over both array to re-add metadata will probably kill performances..

Thanks

**Comment by urschrei** [comment]
As I said, the underlying Rust library RDP implementation cannot currently return indices – I have a [PR](https://github.com/georust/geo/pull/402) that enables it hopefully ready to merge, but there's no workaround until then.

**Comment by eLvErDe** [comment]
Nice, I see the PR has been merged :+1:
